---
- name: installation of dbstandolone for mongodb
  hosts: 104.197.0.78  
  become: yes
  become_method: sudo
  tasks:
  - name: Import the public key used by the package management system
    apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80 
      id: 7F0CEB10 
      state: present
  - name: Add mongo sources list
    sudo: yes
    lineinfile: 
      line: deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse
      dest: /etc/apt/sources.list.d/mongodb.list
      state: present
      create: yes
  - name: install mongodb
    apt:
     pkg: mongodb-org
     state: latest
     update_cache: yes
    notify:
     - start mongodb
  handlers:
  - name: start mongodb
    service:
      name: mongodb-orgi
      state: started
